name: wildfires-etl

on:
  workflow_dispatch
  # schedule:
  #   - cron: '11 * * * *' # runs every hour on the 11th minute

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id token: write
      issues: write
      metadata: write
      packages: write
      pull requests: write
      repository projects: write
      security events: write
      statuses: write
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' # install the python version needed
          
      - name: install things
        run: |
          python -m pip install --upgrade pip
          pip install pandas geopandas fiona mapbox-tilesets mapboxcli
          git clone https://github.com/mapbox/tippecanoe.git
          cd tippecanoe
          make -j
          make install
          
      - name: execute py script # run etl.py to get the latest data
        env: 
          TOKEN: ${{ secrets.MAPBOX_TOKEN_CLI }}
        run: python california-wildfires-map/etl/etl.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main